		<footer class="flex">
            <div class="left">
                <ul class="map none-list-style">
                    <li class="map-item"> <a href="login.html">Log-in</a></li>
                    <li class="map-item"><a href="signup.html">Sign-up</a></li>
                    <li class="map-item"> <a href="https://www.openstreetmap.org">OpenStreetMap</a></li>
                    <li class="map-item"> <a href="https://www.data.brisbane.qld.gov.au/">Open Data</a></li>
                </ul>
            </div>
            <div class="right">
                <ul class="legal none-list-style">
                    <li class="legal-item">OpenStreetMap® is open data, licensed under the Open Data Commons Open Database License (ODbL) by the OpenStreetMap Foundation (OsmallF).</li>
                    <li class="legal-item">Park facilities and assets is open data, licensed under the Creative Commons Attribution 4.0 by the Brisbane City Council.</li>
                </ul>
            </div>
        </footer>	
    </div>